#!/usr/bin/env python3

import time
import logging
import psutil
import requests
import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# CONFIG (можно заменить import из config.py)
# config.py

CPU_THRESHOLD = 60.0
RAM_THRESHOLD = 60.0
LOG_FILE = "/home/ivan/resource_monitor.log"


logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s CPU: %(message)s"
)

def send_alert(message):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {"chat_id": TELEGRAM_CHAT_ID, "text": message}
    try:
        requests.post(url, data=payload)
    except Exception as e:
        with open("/tmp/telegram_error.log", "a") as f:
            f.write(str(e) + "\n")

def monitor():
    while True:
        cpu = psutil.cpu_percent(interval=1)
        mem = psutil.virtual_memory().percent
        logging.info(f"{cpu}% | RAM: {mem}%")
        if cpu > CPU_THRESHOLD:
            send_alert(f"⚠️ High CPU usage: {cpu}%")
        if mem > RAM_THRESHOLD:
            send_alert(f"⚠️ High RAM usage: {mem}%")
        time.sleep(30)

if __name__ == "__main__":
    monitor()
